title: Study Rooms at Townsville University Library
description:  Welcome to the Townsville University Study Rooms microsite! Search for and reserve a study room, find a study group, sign up for tutoring, and more!
baseurl: '/GAstudyareas'
collections:
  studyareas:
    output: true
    permalink: /studyareas/:name/
    
      
# Build settings
markdown: kramdown
theme: minima
plugins: 
- jekyll-feed
  


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
